export interface PriceEntry {
  store: string
  storeUrl: string
  price: number // RON
  url: string // link afiliat sau direct
  inStock: boolean
  lastUpdated: string // "2026-03-19"
}

export interface Supplement {
  id: string
  name: string
  brand: string
  category: 'proteina' | 'creatina' | 'bcaa' | 'omega3' | 'vitamine' | 'preworkout' | 'alte'
  subcategory?: string
  weight?: string // "1kg", "500g"
  servings?: number
  pricePerServing?: number // calculat
  description: string
  benefits: string[]
  forGoal: ('bulk' | 'cut' | 'sanatate' | 'forta')[]
  rating: number // 1-5
  reviewCount: number
  image?: string // URL unsplash sau placeholder
  gymbroRecommended?: boolean
  prices: PriceEntry[]
  tags: string[]
}

export const supplements: Supplement[] = [
  // PROTEINE
  {
    id: 'myprotein-impact-whey-1kg',
    name: 'Impact Whey Protein 1kg',
    brand: 'Myprotein',
    category: 'proteina',
    weight: '1kg',
    servings: 40,
    description: 'Proteina whey concentrate de baza, raport calitate-pret excelent. 21g proteina per portie.',
    benefits: ['21g proteina/portie', '103 kcal/portie', 'Absorbtie rapida', '30+ arome disponibile'],
    forGoal: ['bulk', 'cut', 'forta'],
    rating: 4.5,
    reviewCount: 12400,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 149, url: 'https://www.myprotein.com/ro/sports-nutrition/impact-whey-protein/10530943.html', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 179, url: 'https://www.emag.ro/search/myprotein+impact+whey', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 169, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['whey', 'proteina', 'myprotein', 'incepatori'],
  },
  {
    id: 'on-gold-standard-whey-908g',
    name: 'Gold Standard 100% Whey 908g',
    brand: 'Optimum Nutrition',
    category: 'proteina',
    weight: '908g',
    servings: 29,
    description: 'Cea mai premiata proteina din lume. Whey izolat + concentrat, textura fina, gust excelent.',
    benefits: ['24g proteina/portie', 'Whey izolat ca sursa principala', 'Digestie usoara', 'Brand #1 mondial'],
    forGoal: ['bulk', 'cut', 'forta'],
    rating: 4.8,
    reviewCount: 45000,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 219, url: 'https://www.myprotein.com/ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 229, url: 'https://www.emag.ro/search/optimum+nutrition+gold+standard', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'megaproteine.ro', storeUrl: 'https://www.megaproteine.ro/', price: 224, url: 'https://www.megaproteine.ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 239, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['whey', 'izolat', 'optimum nutrition', 'premium'],
  },
  {
    id: 'olimp-whey-protein-complex-2270g',
    name: 'Whey Protein Complex 2270g',
    brand: 'Olimp',
    category: 'proteina',
    weight: '2.27kg',
    servings: 75,
    description: 'Proteina romaneasca cu raport cantitate-pret exceptional. 78 portii, brand de incredere.',
    benefits: ['25.6g proteina/portie', 'Pret per portie mic', 'Brand romanesc', 'Disponibil in multe magazine'],
    forGoal: ['bulk', 'forta'],
    rating: 4.3,
    reviewCount: 8900,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 279, url: 'https://www.emag.ro/search/olimp+whey+protein', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 269, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 289, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['whey', 'olimp', 'romanesc', 'bulk'],
  },
  // CREATINA
  {
    id: 'myprotein-creatine-monohydrate-250g',
    name: 'Creatine Monohydrate 250g',
    brand: 'Myprotein',
    category: 'creatina',
    weight: '250g',
    servings: 50,
    description: 'Creatina monohidrat pura, micronizata. Cel mai studiat supliment pentru forta si masa musculara.',
    benefits: ['5g creatina/portie', 'Forma monohidrat dovedita', 'Creste forta cu 5-15%', 'Fara arome inutile'],
    forGoal: ['bulk', 'forta'],
    rating: 4.7,
    reviewCount: 18000,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 39, url: 'https://www.myprotein.com/ro/sports-nutrition/creatine-monohydrate/10852456.html', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 55, url: 'https://www.emag.ro/search/myprotein+creatina', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 48, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['creatina', 'monohidrat', 'forta', 'myprotein'],
  },
  {
    id: 'olimp-creatine-xplode-500g',
    name: 'Creatine Xplode 500g',
    brand: 'Olimp',
    category: 'creatina',
    weight: '500g',
    servings: 50,
    description: 'Mix de 6 forme de creatina pentru absorbtie maxima. Popular printre atletii romani.',
    benefits: ['Mix 6 forme creatina', 'Absorbtie optimizata', 'Cu taurina si vitamina B6', 'Disponibil cu arome'],
    forGoal: ['forta', 'bulk'],
    rating: 4.4,
    reviewCount: 5600,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 109, url: 'https://www.emag.ro/search/olimp+creatine+xplode', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 99, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 115, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['creatina', 'olimp', 'mix', 'premium'],
  },
  // OMEGA-3
  {
    id: 'now-foods-omega3-200caps',
    name: 'Omega-3 1000mg 200 capsule',
    brand: 'NOW Foods',
    category: 'omega3',
    weight: '200 caps',
    servings: 100,
    description: 'Omega-3 de inalta calitate de la NOW Foods. EPA + DHA pentru sanatate cardiovasculara si articulatii.',
    benefits: ['EPA 180mg + DHA 120mg', 'Sanatate cardiovasculara', 'Anti-inflamator', 'Articulatii sanatoase'],
    forGoal: ['sanatate', 'cut'],
    rating: 4.6,
    reviewCount: 9200,
    gymbroRecommended: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 79, url: 'https://ro.iherb.com/pr/now-foods-omega-3/742', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 95, url: 'https://www.emag.ro/search/now+foods+omega3', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 89, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['omega3', 'sanatate', 'now foods', 'iherb'],
  },
  // VITAMINE
  {
    id: 'now-foods-vitamin-d3-5000iu',
    name: 'Vitamin D3 5000 IU 240 softgels',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 240,
    description: 'Vitamina D3 in doza optima. Esentiala pentru romani din cauza expunerii solare reduse.',
    benefits: ['5000 IU per capsula', 'Imunitate + oase', 'Testat de terte parti', '240 zile dintr-un flacon'],
    forGoal: ['sanatate'],
    rating: 4.8,
    reviewCount: 22000,
    gymbroRecommended: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 55, url: 'https://ro.iherb.com/pr/now-foods-vitamin-d-3/1489', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 75, url: 'https://www.emag.ro/search/vitamina+d3+5000', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['vitamina d3', 'imunitate', 'now foods', 'iherb'],
  },
  // PREWORKOUT
  {
    id: 'myprotein-the-pre-workout-300g',
    name: 'THE Pre-Workout 300g',
    brand: 'Myprotein',
    category: 'preworkout',
    weight: '300g',
    servings: 30,
    description: 'Pre-workout complet cu cafeina, beta-alanina si creatina. Energie si focus pentru antrenamente intense.',
    benefits: ['200mg cafeina/portie', 'Beta-alanina 3.2g', 'Creatina 3g', 'Fara zahar'],
    forGoal: ['forta', 'cut'],
    rating: 4.3,
    reviewCount: 6700,
    image: 'https://images.unsplash.com/photo-1544991875-5dc1b05f1571?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 119, url: 'https://www.myprotein.com/ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 139, url: 'https://www.emag.ro/search/myprotein+preworkout', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['preworkout', 'cafeina', 'energie', 'myprotein'],
  },
  // BCAA
  {
    id: 'myprotein-bcaa-250g',
    name: 'BCAA 2:1:1 250g',
    brand: 'Myprotein',
    category: 'bcaa',
    weight: '250g',
    servings: 50,
    description: 'Aminoacizi esentiali ramificati in raport optimal 2:1:1. Recuperare musculara si anti-catabolism.',
    benefits: ['5g BCAA/portie', 'Raport 2:1:1 Leucina:Izoleucina:Valina', 'Recuperare mai rapida', 'Protejeaza masa musculara'],
    forGoal: ['cut', 'forta'],
    rating: 4.2,
    reviewCount: 8100,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 59, url: 'https://www.myprotein.com/ro/', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 79, url: 'https://www.emag.ro/search/myprotein+bcaa', inStock: true, lastUpdated: '2026-03-19' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 69, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-19' },
    ],
    tags: ['bcaa', 'recuperare', 'aminoacizi', 'myprotein'],
  },

  // ── PROTEINE EXTINSE ──────────────────────────────────────────────────────
  {
    id: 'dymatize-iso100-726g',
    name: 'ISO 100 Hydrolyzed 726g',
    brand: 'Dymatize',
    category: 'proteina',
    weight: '726g',
    servings: 29,
    description: 'Proteina izolat hidrolizat premium de la Dymatize. 25g proteina per portie, absorbtie ultra-rapida datorita hidrolizei.',
    benefits: ['25g proteina/portie', 'Izolat hidrolizat premium', 'Absorbtie ultra-rapida', 'Sub 1g zahar/portie'],
    forGoal: ['cut', 'forta', 'bulk'],
    rating: 4.7,
    reviewCount: 14200,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 289, url: 'https://www.emag.ro/search/dymatize+iso+100', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'megaproteine.ro', storeUrl: 'https://www.megaproteine.ro/', price: 279, url: 'https://www.megaproteine.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 299, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['whey', 'izolat', 'hidrolizat', 'dymatize', 'premium'],
  },
  {
    id: 'myprotein-clear-whey-isolate-500g',
    name: 'Clear Whey Isolate 500g',
    brand: 'Myprotein',
    category: 'proteina',
    weight: '500g',
    servings: 20,
    description: 'Proteina tip "suc" — textura usoara si racoritoare, nu cremos. Tendinta majora 2024-2026 in lumea fitness.',
    benefits: ['20g proteina/portie', 'Textura de suc, nu shake', 'Izolat de zer pur', 'Ideal vara sau post-antrenament'],
    forGoal: ['cut', 'forta'],
    rating: 4.5,
    reviewCount: 7800,
    image: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 189, url: 'https://www.myprotein.com/ro/sports-nutrition/clear-whey-isolate/13050027.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 219, url: 'https://www.emag.ro/search/myprotein+clear+whey', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['clear whey', 'izolat', 'myprotein', 'trend', 'vegan-friendly'],
  },
  {
    id: 'biotech-usa-iso-whey-zero-500g',
    name: 'Iso Whey Zero 500g',
    brand: 'Biotech USA',
    category: 'proteina',
    weight: '500g',
    servings: 20,
    description: 'Izolat whey fara lactoza de la Biotech USA, brand european popular in Romania. Ideal pentru persoane cu intoleranta la lactoza.',
    benefits: ['23g proteina/portie', 'Fara lactoza', 'Fara zahar adaugat', 'Brand european de incredere'],
    forGoal: ['cut', 'forta', 'sanatate'],
    rating: 4.4,
    reviewCount: 5300,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    prices: [
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 149, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 159, url: 'https://www.emag.ro/search/biotech+iso+whey+zero', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 155, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['izolat', 'fara lactoza', 'biotech usa', 'european'],
  },
  {
    id: 'kevin-levrone-anabolic-mass-3kg',
    name: 'Anabolic Mass 3kg',
    brand: 'Kevin Levrone',
    category: 'proteina',
    weight: '3kg',
    servings: 30,
    description: 'Mass gainer serios pentru bulk — calorii dense, proteine si carbohidrati pentru crestere musculara rapida.',
    benefits: ['50g proteina/portie', 'Calorii dense pentru bulk', 'Creatina si BCAA incluse', '3kg — stoc pentru luni'],
    forGoal: ['bulk'],
    rating: 4.3,
    reviewCount: 3100,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    prices: [
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 199, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 219, url: 'https://www.emag.ro/search/kevin+levrone+anabolic+mass', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['mass gainer', 'bulk', 'kevin levrone', 'calorii'],
  },
  {
    id: 'myprotein-vegan-protein-blend-1kg',
    name: 'Vegan Protein Blend 1kg',
    brand: 'Myprotein',
    category: 'proteina',
    weight: '1kg',
    servings: 33,
    description: 'Proteina vegana din mazare si orez — profil complet de aminoacizi, fara produse de origine animala.',
    benefits: ['22g proteina/portie', 'Pea + Rice protein blend', 'Profil complet aminoacizi', '100% vegan'],
    forGoal: ['bulk', 'cut', 'sanatate'],
    rating: 4.2,
    reviewCount: 4700,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 159, url: 'https://www.myprotein.com/ro/sports-nutrition/vegan-protein-blend/10696024.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 189, url: 'https://www.emag.ro/search/myprotein+vegan+protein', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['vegan', 'proteina', 'mazare', 'orez', 'myprotein', 'plant-based'],
  },

  // ── CREATINA EXTINSA ──────────────────────────────────────────────────────
  {
    id: 'myprotein-creapure-500g',
    name: 'Creapure Creatine Monohydrate 500g',
    brand: 'Myprotein',
    category: 'creatina',
    weight: '500g',
    servings: 100,
    description: 'Creatina certificata Creapure — cea mai pura forma de creatina monohidrat disponibila pe piata. Produsa in Germania.',
    benefits: ['Certificata Creapure', 'Puritate 99.99%', '5g creatina/portie', '100 portii — 100 zile stoc'],
    forGoal: ['forta', 'bulk'],
    rating: 4.9,
    reviewCount: 28000,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 89, url: 'https://www.myprotein.com/ro/sports-nutrition/creapure-creatine/10852500.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 109, url: 'https://www.emag.ro/search/creapure+creatina', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['creatina', 'creapure', 'premium', 'germania', 'myprotein'],
  },
  {
    id: 'biotech-usa-creatine-monohydrate-300g',
    name: 'Creatine Monohydrate 300g',
    brand: 'Biotech USA',
    category: 'creatina',
    weight: '300g',
    servings: 60,
    description: 'Creatina monohidrat simpla de la Biotech USA. Optiune budget-friendly pentru cei care incep cu suplimentarea.',
    benefits: ['5g creatina/portie', 'Pret accesibil', 'Forma monohidrat clasica', 'Fara aditivi'],
    forGoal: ['forta', 'bulk'],
    rating: 4.2,
    reviewCount: 2800,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop',
    prices: [
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 49, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 59, url: 'https://www.emag.ro/search/biotech+creatine+monohydrate', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['creatina', 'budget', 'biotech usa', 'incepatori'],
  },
  {
    id: 'now-foods-creatine-powder-500g',
    name: 'Creatine Powder 500g',
    brand: 'NOW Foods',
    category: 'creatina',
    weight: '500g',
    servings: 100,
    description: 'Creatina monohidrat de la NOW Foods — brand american de incredere, testat de terte parti pentru puritate.',
    benefits: ['5g creatina/portie', 'Brand american de incredere', 'Testat de terte parti', '100 portii per cutie'],
    forGoal: ['forta', 'bulk'],
    rating: 4.6,
    reviewCount: 11500,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 89, url: 'https://ro.iherb.com/pr/now-foods-creatine-powder/467', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 99, url: 'https://www.emag.ro/search/now+foods+creatine', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['creatina', 'now foods', 'iherb', 'us brand'],
  },

  // ── VITAMINE & MINERALE ───────────────────────────────────────────────────
  {
    id: 'now-foods-vitamin-c-1000mg-100tabs',
    name: 'Vitamin C 1000mg 100 tablete',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 100,
    description: 'Vitamina C 1000mg cu bioflavonoide — imunitate, antioxidant puternic, recuperare dupa antrenament.',
    benefits: ['1000mg Vitamina C/portie', 'Cu bioflavonoide naturale', 'Antioxidant puternic', 'Suport imunitar'],
    forGoal: ['sanatate'],
    rating: 4.7,
    reviewCount: 19000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 39, url: 'https://ro.iherb.com/pr/now-foods-vitamin-c-1000/687', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 55, url: 'https://www.emag.ro/search/now+foods+vitamina+c+1000', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 49, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['vitamina c', 'imunitate', 'antioxidant', 'now foods'],
  },
  {
    id: 'now-foods-zinc-50mg-100tabs',
    name: 'Zinc 50mg 100 tablete',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 100,
    description: 'Zinc gluconat 50mg — esential pentru niveluri optime de testosteron, imunitate si recuperare.',
    benefits: ['50mg Zinc gluconat/portie', 'Suport testosteron natural', 'Imunitate puternica', 'Recuperare accelerata'],
    forGoal: ['sanatate', 'forta'],
    rating: 4.6,
    reviewCount: 13000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 29, url: 'https://ro.iherb.com/pr/now-foods-zinc/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 45, url: 'https://www.emag.ro/search/now+foods+zinc+50mg', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['zinc', 'testosteron', 'imunitate', 'now foods', 'mineral'],
  },
  {
    id: 'now-foods-magnesium-citrate-120caps',
    name: 'Magnesium Citrate 120 capsule',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 60,
    description: 'Magneziu citrat — forma cu biodisponibilitate ridicata. Esential pentru somn de calitate, recuperare si prevenirea crampelor.',
    benefits: ['400mg Magneziu citrat/portie', 'Forma cu absorbtie superioara', 'Somn mai bun', 'Previne crampele musculare'],
    forGoal: ['sanatate', 'forta'],
    rating: 4.7,
    reviewCount: 16800,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 49, url: 'https://ro.iherb.com/pr/now-foods-magnesium-citrate/737', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 65, url: 'https://www.emag.ro/search/now+foods+magnesium+citrate', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['magneziu', 'somn', 'recuperare', 'crampe', 'now foods'],
  },
  {
    id: 'olimp-gold-omega-3-6-9-90caps',
    name: 'Gold Omega 3-6-9 90 capsule',
    brand: 'Olimp',
    category: 'omega3',
    servings: 30,
    description: 'Complex complet Omega 3-6-9 de la Olimp. Acizi grasi esentiali pentru sanatate cardiovasculara, articulatii si creier.',
    benefits: ['Omega 3, 6 si 9 intr-o capsule', 'EPA + DHA + GLA + ALA', 'Sanatate cardiovasculara', 'Anti-inflamator natural'],
    forGoal: ['sanatate'],
    rating: 4.4,
    reviewCount: 4200,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 69, url: 'https://www.emag.ro/search/olimp+omega+3+6+9', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 59, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 75, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['omega 3', 'omega 6', 'omega 9', 'olimp', 'sanatate'],
  },
  {
    id: 'now-foods-b-complex-100caps',
    name: 'B-Complex 100 capsule',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 100,
    description: 'Complex complet de vitamine B pentru energie, metabolism si sanatatea sistemului nervos.',
    benefits: ['Toate vitaminele B intr-o capsula', 'Energie si metabolism optim', 'Sanatate sistem nervos', '100 zile stoc'],
    forGoal: ['sanatate'],
    rating: 4.6,
    reviewCount: 9800,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 55, url: 'https://ro.iherb.com/pr/now-foods-b-complex/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 75, url: 'https://www.emag.ro/search/now+foods+b+complex', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['vitamina b', 'energie', 'metabolism', 'now foods', 'complex'],
  },
  {
    id: 'centrum-men-30tabs',
    name: 'Centrum Men 30 tablete',
    brand: 'Centrum',
    category: 'vitamine',
    servings: 30,
    description: 'Multivitamine complete formulate special pentru barbati activi. Toate vitaminele si mineralele esentiale intr-o tableta.',
    benefits: ['Formula specifica barbatilor', '23+ vitamine si minerale', 'Energie si vitalitate', 'Recomandat de medici'],
    forGoal: ['sanatate'],
    rating: 4.3,
    reviewCount: 6500,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 55, url: 'https://www.emag.ro/search/centrum+men', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG Farmacie', storeUrl: 'https://www.emag.ro/', price: 59, url: 'https://www.emag.ro/search/centrum+men+farmacie', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['multivitamine', 'barbati', 'centrum', 'sanatate', 'vitalitate'],
  },
  {
    id: 'now-foods-iron-18mg-120caps',
    name: 'Iron 18mg 120 capsule',
    brand: 'NOW Foods',
    category: 'vitamine',
    servings: 120,
    description: 'Fier bisglicinnat 18mg — forma cu absorbtie superioara, fara efecte secundare gastrice. Ideal pentru femei active.',
    benefits: ['18mg Fier bisglicinnat', 'Absorbtie superioara', 'Nu cauzeza constipatie', 'Ideal pentru femei active'],
    forGoal: ['sanatate'],
    rating: 4.5,
    reviewCount: 7300,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 25, url: 'https://ro.iherb.com/pr/now-foods-iron/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 39, url: 'https://www.emag.ro/search/now+foods+fier+iron', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['fier', 'femei', 'anemie', 'now foods', 'energie'],
  },

  // ── BCAA & AMINOACIZI EXTINSE ─────────────────────────────────────────────
  {
    id: 'olimp-bcaa-xplode-500g',
    name: 'BCAA Xplode Powder 500g',
    brand: 'Olimp',
    category: 'bcaa',
    weight: '500g',
    servings: 50,
    description: 'BCAA cu glutamina si vitamina B6 de la Olimp — cel mai popular BCAA din Romania. Absorbtie rapida, arome gustoase.',
    benefits: ['5g BCAA 2:1:1 /portie', '+Glutamina pentru recuperare', 'Vitamina B6 inclusa', 'Disponibil in 10+ arome'],
    forGoal: ['cut', 'forta'],
    rating: 4.5,
    reviewCount: 11200,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 119, url: 'https://www.emag.ro/search/olimp+bcaa+xplode', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 109, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 125, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['bcaa', 'olimp', 'glutamina', 'recuperare', 'romanesc'],
  },
  {
    id: 'now-foods-l-glutamine-454g',
    name: 'L-Glutamine Powder 454g',
    brand: 'NOW Foods',
    category: 'bcaa',
    weight: '454g',
    servings: 90,
    description: 'L-Glutamina pura in forma pudra de la NOW Foods. Recuperare musculara, sanatatea intestinului si imunitate.',
    benefits: ['5g L-Glutamina/portie', 'Recuperare musculara rapida', 'Sanatatea tractului intestinal', 'Suport imunitar'],
    forGoal: ['cut', 'sanatate'],
    rating: 4.6,
    reviewCount: 8900,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 99, url: 'https://ro.iherb.com/pr/now-foods-l-glutamine/457', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 129, url: 'https://www.emag.ro/search/now+foods+glutamine', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['glutamina', 'recuperare', 'intestin', 'now foods', 'aminoacid'],
  },
  {
    id: 'myprotein-l-glutamine-250g',
    name: 'L-Glutamine 250g',
    brand: 'Myprotein',
    category: 'bcaa',
    weight: '250g',
    servings: 50,
    description: 'Glutamina pura micronizata de la Myprotein. Aminoacidul cel mai abundent in organism, esential dupa antrenamente intense.',
    benefits: ['5g Glutamina pura/portie', 'Micronizata pentru dizolvare usoara', 'Recuperare si anti-catabolism', 'Fara aditivi'],
    forGoal: ['cut', 'sanatate'],
    rating: 4.4,
    reviewCount: 5600,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 49, url: 'https://www.myprotein.com/ro/sports-nutrition/l-glutamine/10852457.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 69, url: 'https://www.emag.ro/search/myprotein+glutamina', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['glutamina', 'myprotein', 'recuperare', 'aminoacid'],
  },
  {
    id: 'biotech-usa-bcaa-flash-zero-360g',
    name: 'BCAA Flash Zero 360g',
    brand: 'Biotech USA',
    category: 'bcaa',
    weight: '360g',
    servings: 60,
    description: 'BCAA instant dissolve fara zahar de la Biotech USA. Dizolvare instantanee, fara calorii inutile.',
    benefits: ['6g BCAA/portie', 'Instant dissolve', 'Zero zahar', 'Electroliti inclusi'],
    forGoal: ['cut', 'forta'],
    rating: 4.3,
    reviewCount: 3200,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    prices: [
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 89, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 99, url: 'https://www.emag.ro/search/biotech+bcaa+flash', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['bcaa', 'biotech usa', 'fara zahar', 'instant'],
  },

  // ── PRE-WORKOUT EXTINS ────────────────────────────────────────────────────
  {
    id: 'olimp-redweiler-480g',
    name: 'Redweiler 480g',
    brand: 'Olimp',
    category: 'preworkout',
    weight: '480g',
    servings: 30,
    description: 'Pre-workout puternic de la Olimp — cel mai popular pre-workout din Romania. Energie, forta si focus extrem.',
    benefits: ['300mg cafeina/portie', 'Beta-alanina 3.2g', 'Arginina + citrulina', 'Pump maxim garantat'],
    forGoal: ['forta', 'bulk'],
    rating: 4.6,
    reviewCount: 9400,
    image: 'https://images.unsplash.com/photo-1544991875-5dc1b05f1571?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 149, url: 'https://www.emag.ro/search/olimp+redweiler', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 139, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'fitshop.ro', storeUrl: 'https://www.fitshop.ro/', price: 155, url: 'https://www.fitshop.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['preworkout', 'olimp', 'romanesc', 'cafeina', 'energie', 'pump'],
  },
  {
    id: 'biotech-usa-black-blood-nox-330g',
    name: 'Black Blood NOX+ 330g',
    brand: 'Biotech USA',
    category: 'preworkout',
    weight: '330g',
    servings: 30,
    description: 'Pre-workout de intensitate mare de la Biotech USA. Formula avansata pentru antrenamente extreme.',
    benefits: ['250mg cafeina/portie', 'NO boosteri puternici', 'Beta-alanina + citrulina', 'Energie de lunga durata'],
    forGoal: ['forta'],
    rating: 4.4,
    reviewCount: 4100,
    image: 'https://images.unsplash.com/photo-1544991875-5dc1b05f1571?w=400&h=400&fit=crop',
    prices: [
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 129, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 139, url: 'https://www.emag.ro/search/biotech+black+blood+nox', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['preworkout', 'biotech usa', 'intensitate', 'no booster'],
  },
  {
    id: 'now-foods-energy-90caps',
    name: 'Energy 90 capsule',
    brand: 'NOW Foods',
    category: 'preworkout',
    servings: 45,
    description: 'Energie naturala fara stimulanti puternici. Ideal pentru cei sensibili la cafeina sau pentru antrenamente seara.',
    benefits: ['Energie naturala sustinuta', 'Fara stimulanti puternici', 'Adaptogeni naturali', 'Sigur pentru antrenamente seara'],
    forGoal: ['forta', 'sanatate'],
    rating: 4.1,
    reviewCount: 3400,
    image: 'https://images.unsplash.com/photo-1544991875-5dc1b05f1571?w=400&h=400&fit=crop',
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 79, url: 'https://ro.iherb.com/pr/now-foods-energy/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 99, url: 'https://www.emag.ro/search/now+foods+energy', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['energie', 'natural', 'stimulanti', 'now foods', 'fara cafeina'],
  },

  // ── ZMA / SOMN / RECUPERARE ───────────────────────────────────────────────
  {
    id: 'now-foods-zma-90caps',
    name: 'ZMA 90 capsule',
    brand: 'NOW Foods',
    category: 'alte',
    subcategory: 'recuperare',
    servings: 30,
    description: 'Zinc + Magneziu + Vitamina B6 — formula clasica ZMA pentru testosteron natural, somn profund si recuperare musculara.',
    benefits: ['Zinc 30mg + Magneziu 450mg + B6 10.5mg', 'Testosteron natural optimizat', 'Somn profund si recuperare', 'Formula patentata ZMA'],
    forGoal: ['forta', 'sanatate'],
    rating: 4.5,
    reviewCount: 12000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 75, url: 'https://ro.iherb.com/pr/now-foods-zma/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 99, url: 'https://www.emag.ro/search/now+foods+zma', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['zma', 'zinc', 'magneziu', 'testosteron', 'somn', 'now foods'],
  },
  {
    id: 'myprotein-zma-90caps',
    name: 'ZMA 90 capsule',
    brand: 'Myprotein',
    category: 'alte',
    subcategory: 'recuperare',
    servings: 30,
    description: 'Formula ZMA extinsa de la Myprotein cu Ashwagandha — zinc, magneziu, B6 plus extract de ashwagandha pentru recuperare si somn.',
    benefits: ['ZMA clasic + Ashwagandha', 'Cortizol redus', 'Recuperare superioara', 'Testosteron si somn optimizate'],
    forGoal: ['forta', 'sanatate'],
    rating: 4.4,
    reviewCount: 4700,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 89, url: 'https://www.myprotein.com/ro/sports-nutrition/zma/10852458.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 109, url: 'https://www.emag.ro/search/myprotein+zma', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['zma', 'ashwagandha', 'testosteron', 'somn', 'myprotein'],
  },
  {
    id: 'now-foods-melatonin-3mg-180tabs',
    name: 'Melatonin 3mg 180 tablete',
    brand: 'NOW Foods',
    category: 'alte',
    subcategory: 'somn',
    servings: 180,
    description: 'Melatonina 3mg pentru reglarea ritmului circadian si somn natural. Ideal pentru schimbari de fus orar sau program haotic.',
    benefits: ['3mg Melatonina/tableta', 'Somn natural fara dependenta', '180 zile stoc', 'Regleaza ritmul circadian'],
    forGoal: ['sanatate'],
    rating: 4.6,
    reviewCount: 21000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 35, url: 'https://ro.iherb.com/pr/now-foods-melatonin-3-mg/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 55, url: 'https://www.emag.ro/search/now+foods+melatonin', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['melatonina', 'somn', 'recuperare', 'now foods', 'noapte'],
  },

  // ── COLAGEN & ARTICULATII ─────────────────────────────────────────────────
  {
    id: 'now-foods-collagen-peptides-227g',
    name: 'Collagen Peptides 227g',
    brand: 'NOW Foods',
    category: 'alte',
    subcategory: 'articulatii',
    weight: '227g',
    servings: 20,
    description: 'Colagen hidrolizat de tip I si III — piele, articulatii, oase si tendoane. Peptide cu absorbtie superioara.',
    benefits: ['Colagen hidrolizat tip I & III', 'Piele mai elastica', 'Articulatii protejate', 'Tendoane si ligamente sanatoase'],
    forGoal: ['sanatate'],
    rating: 4.5,
    reviewCount: 8700,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 119, url: 'https://ro.iherb.com/pr/now-foods-collagen-peptides/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 149, url: 'https://www.emag.ro/search/now+foods+colagen+peptides', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['colagen', 'articulatii', 'piele', 'now foods', 'peptide'],
  },
  {
    id: 'myprotein-collagen-protein-240g',
    name: 'Collagen Protein 240g',
    brand: 'Myprotein',
    category: 'alte',
    subcategory: 'articulatii',
    weight: '240g',
    servings: 30,
    description: 'Colagen hidrolizat cu Vitamina C de la Myprotein. Vitamina C ajuta la sinteza colagenului pentru eficienta maxima.',
    benefits: ['Colagen hidrolizat', 'Vitamina C inclusa', 'Sinteza colagenului optimizata', 'Arome gustoase'],
    forGoal: ['sanatate'],
    rating: 4.3,
    reviewCount: 3800,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 99, url: 'https://www.myprotein.com/ro/sports-nutrition/collagen-protein/12619767.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 129, url: 'https://www.emag.ro/search/myprotein+colagen', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['colagen', 'vitamina c', 'articulatii', 'myprotein'],
  },
  {
    id: 'now-foods-glucosamine-chondroitin-90tabs',
    name: 'Glucosamine & Chondroitin 90 tablete',
    brand: 'NOW Foods',
    category: 'alte',
    subcategory: 'articulatii',
    servings: 45,
    description: 'Glucozamina si condroitina — combinatia clasica pentru sanatatea articulatiilor. Popular la sportivii de +35 ani.',
    benefits: ['Glucozamina 1500mg + Condroitina 1200mg', 'Cartilaj articular protejat', 'Reduce durerile articulare', 'Mobilitatate imbunatatita'],
    forGoal: ['sanatate'],
    rating: 4.4,
    reviewCount: 9100,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 99, url: 'https://ro.iherb.com/pr/now-foods-glucosamine-chondroitin/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 129, url: 'https://www.emag.ro/search/now+foods+glucozamina+condroitina', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['glucozamina', 'condroitina', 'articulatii', 'now foods', 'senior'],
  },

  // ── ARDERE GRASIMI ────────────────────────────────────────────────────────
  {
    id: 'olimp-thermo-speed-extreme-120caps',
    name: 'Thermo Speed Extreme 120 capsule',
    brand: 'Olimp',
    category: 'alte',
    subcategory: 'ardere grasimi',
    servings: 30,
    description: 'Termogenic puternic de la Olimp — cel mai popular fat burner din Romania. Ardere grasimi, energie si supresie apetit.',
    benefits: ['Formula termogenica puternica', 'Suprima apetitul', 'Energie si focus', 'Extract de cafea verde'],
    forGoal: ['cut'],
    rating: 4.4,
    reviewCount: 7600,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 119, url: 'https://www.emag.ro/search/olimp+thermo+speed', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'allnutrition.ro', storeUrl: 'https://allnutrition.ro/', price: 109, url: 'https://allnutrition.ro/', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['fat burner', 'termogenic', 'olimp', 'cut', 'slabire'],
  },
  {
    id: 'now-foods-l-carnitine-500mg-60caps',
    name: 'L-Carnitine 500mg 60 capsule',
    brand: 'NOW Foods',
    category: 'alte',
    subcategory: 'ardere grasimi',
    servings: 60,
    description: 'L-Carnitina 500mg — transporta acizii grasi in mitocondrii pentru ardere eficienta. Suport pentru energie si slabire.',
    benefits: ['500mg L-Carnitina/capsula', 'Transport acizi grasi in mitocondrii', 'Energie din grasimi', 'Suport cardiovascular'],
    forGoal: ['cut', 'sanatate'],
    rating: 4.5,
    reviewCount: 11000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 79, url: 'https://ro.iherb.com/pr/now-foods-l-carnitine/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 99, url: 'https://www.emag.ro/search/now+foods+l+carnitina', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['l-carnitina', 'ardere grasimi', 'cut', 'now foods', 'slabire'],
  },
  {
    id: 'myprotein-cla-1000mg-90softgels',
    name: 'CLA 1000mg 90 softgels',
    brand: 'Myprotein',
    category: 'alte',
    subcategory: 'ardere grasimi',
    servings: 45,
    description: 'Acid linoleic conjugat (CLA) 1000mg — ajuta la reducerea grasimii corporale si mentinerea masei musculare in deficit caloric.',
    benefits: ['1000mg CLA/softgel', 'Reducere grasime corporala', 'Mentine masa musculara', 'Fara stimulanti'],
    forGoal: ['cut'],
    rating: 4.2,
    reviewCount: 5200,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 69, url: 'https://www.myprotein.com/ro/sports-nutrition/cla/10852459.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 89, url: 'https://www.emag.ro/search/myprotein+cla', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['cla', 'cut', 'slabire', 'myprotein', 'acizi grasi'],
  },

  // ── PROTEINE SPECIALE ─────────────────────────────────────────────────────
  {
    id: 'myprotein-micellar-casein-1kg',
    name: 'Micellar Casein 1kg',
    brand: 'Myprotein',
    category: 'proteina',
    weight: '1kg',
    servings: 40,
    description: 'Proteina caseina micelarala cu absorbtie lenta 6-8 ore. Perfecta inainte de somn pentru anti-catabolism nocturn.',
    benefits: ['Absorbtie lenta 6-8h', 'Anti-catabolism nocturn', '24g proteina/portie', 'Ideal inainte de somn'],
    forGoal: ['bulk', 'cut'],
    rating: 4.5,
    reviewCount: 7200,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'Myprotein', storeUrl: 'https://www.myprotein.com/ro/', price: 169, url: 'https://www.myprotein.com/ro/sports-nutrition/micellar-casein/10530944.html', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 199, url: 'https://www.emag.ro/search/myprotein+caseina', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['caseina', 'proteina lenta', 'noapte', 'anti-catabolism', 'myprotein'],
  },
  {
    id: 'now-foods-pea-protein-544g',
    name: 'Pea Protein 544g',
    brand: 'NOW Foods',
    category: 'proteina',
    weight: '544g',
    servings: 20,
    description: 'Proteina din mazare — 100% vegana, fara alergeni comuni, profil complet de aminoacizi esentiali.',
    benefits: ['24g proteina/portie', '100% vegan si allergen-free', 'Fara gluten si lactoza', 'Proteina din mazare galbena'],
    forGoal: ['bulk', 'cut', 'sanatate'],
    rating: 4.2,
    reviewCount: 4400,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=400&fit=crop',
    gymbroRecommended: true,
    prices: [
      { store: 'iHerb', storeUrl: 'https://ro.iherb.com/', price: 109, url: 'https://ro.iherb.com/pr/now-foods-pea-protein/787', inStock: true, lastUpdated: '2026-03-20' },
      { store: 'eMAG', storeUrl: 'https://www.emag.ro/', price: 139, url: 'https://www.emag.ro/search/now+foods+pea+protein', inStock: true, lastUpdated: '2026-03-20' },
    ],
    tags: ['proteina mazare', 'vegan', 'allergen free', 'now foods', 'plant-based'],
  },
]
